version: "3.9"
services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark_app
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_HOME=/opt/bitnami/spark
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "4040:4040"   
      - "5000:5000"   
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
